### ISSUE TITLE
something is wrong!

### ISSUE THREAD

**Issue by kcujy233** [robotic-vision-lab/Progressive-Conditional-Generative-Adversarial-Network#1]
Actually, I have used various datasets including my own dataset, and I have got similar results like a result of clustering point-clouds. I don't know why.
![image](https://user-images.githubusercontent.com/66406042/162208433-8f7ac0cb-7a3f-438a-b8c7-8d9bde75db21.png)
![image](https://user-images.githubusercontent.com/66406042/162208585-4376922d-3b1a-415b-8410-3ca873e50bf1.png)
the first one is plane, and the second one is a can.

**Comment by samiarshad** [comment]
Hi @kcujy233,

Thanks for your interest in our work. I am finding it difficult to understand the issue from your post. Could you please provide more information? Which dataset did you use to train the model, and how did you preprocessed the data? What is the resolution of the point cloud in the images?

Sami

**Comment by kcujy233** [comment]
I'm so sorry!!! I have made some problems that I have applied the wrong code to show the results. I will try it again. And I have a question that if I increase the generated points(such as from original 1024points to 8192points), what will happen. And how should I adjust my Discriminator. I am so apologized for my errors.

**Comment by samiarshad** [comment]
Increasing resolution from 1024 to, 8192 should increase the output point density. 
The discriminator will be adjusted automatically based on whichever resolution it is currently discriminating.

**Comment by kcujy233** [comment]
Thank you very much for your reply!! It’s my great honor to learn from you. And I have also  encountered some problems:
1.I wonder whether the updated step be affected by batch_size? And whether the updated step inherit the model parameters which have been trained in step0.
2.Although I can read the code, I couldn’t completely understand the Discriminator or the k-nn how to work. From my perspective, maybe the value of **### k**, are the number of the nearest-k-points around the vertex-point? And if I want to generate a sample like a board or flat(with no more features), should I adjust the number **### k** to be smaller?

In fact, the value of mean-loss-functions of the Discriminator and Generator have almost converged, but the results are not entirely ideal. 
This is my first exposure to Generative Adversarial Networks and even Deep Learning. I will appreciate it sincerely if you could answer my question.

**Comment by samiarshad** [comment]
1. Yes
2. Please refer to the paper for more details. The value of K is tuned depending on the experimental results. You can try out different values to accommodate your need.

Since the original problem occurred due to a coding error, I am closing this issue. Please open a separate one if needed.
