### ISSUE TITLE
Ask about the types of datasets in the paper

### ISSUE THREAD

**Issue by wangxin-fighting** [robotic-vision-lab/Progressive-Conditional-Generative-Adversarial-Network#3]
Hello, may I ask which version of the "shapenetcore" is used for the dataset in your paper? I found v1 and v2 on the official website. Looking forward to your reply and wishing you a happy life!

**Comment by samiarshad** [comment]
HI,

Thank you for your interest. We have used the version V1.

Best,
Sami
